spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  show-actuator: false
